# ~/.config/alacritty/alacritty.toml

# Optional: import a theme file
# import = ["~/.config/alacritty/tokyo-night.toml"]

#####################
# General Settings
#####################
[general]
live_config_reload = true

#####################
# Font
#####################
[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 12.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

#####################
# Window & Transparency
#####################
[window]
# `background_opacity` is a legacy option and is deprecated.
# `window.opacity` is the current correct option.
opacity = 0.85
dynamic_title = true

#####################
# Colors: Tokyo Night
#####################
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black   = "#1a1b26"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#bac2de"

#####################
# Scrolling
#####################
[scrolling]
history = 10000
multiplier = 3

#####################
# Visual Bell
#####################
# The section is now called [bell] instead of [visual_bell]
[bell]
animation = "Ease"
color = "#ffffff"

#####################
# Cursor
#####################
[cursor]
# Style is now a table. For blinking, use `blinking = "On"`.
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

#####################
# Selection
#####################
[selection]
# `semantic_escape_chars` is deprecated.
# Use `semantic_word_separators` instead if you need to customize this.
save_to_clipboard = true

#####################
# Optional key bindings (copy/paste)
#####################
# The section is now called [keyboard] instead of [key_bindings]
[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
]
