import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/dotfiles/alacritty/.config/alacritty/catppuccin-macchiato.toml"
  # "~/dotfiles/alacritty/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]


