# Alacritty Configuration File
# Default configuration overrides for Alacritty.

# Color scheme (Dracula theme)
colors:
  primary:
    background: '0x282a36' # Background color
    foreground: '0xf8f8f2' # Foreground color
  cursor:
    text: '0x282a36'
    cursor: '0xf8f8f2'
  normal:
    black:   '0x21222c'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xf8f8f2'
  bright:
    black:   '0x6272a4'
    red:     '0xff6e6e'
    green:   '0x69ff94'
    yellow:  '0xffffa5'
    blue:    '0xd6acff'
    magenta: '0xff92df'
    cyan:    '0xa4ffff'
    white:   '0xffffff'

# Font configuration
font:
  normal:
    family: "Hack Nerd Font"
    style: "Regular"
  bold:
    family: "Hack Nerd Font"
    style: "Bold"
  italic:
    family: "Hack Nerd Font"
    style: "Italic"
  size: 12.0

# Window settings
window:
  opacity: 0.95 # Slight transparency
  decorations: full # Full decorations
  startup_mode: Windowed # Open in a windowed mode
  dimensions:
    columns: 100
    lines: 30

# Scrollback buffer
scrolling:
  history: 10000 # Number of lines in the scrollback buffer

# Key bindings
key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }

