

source $HOME/.config/vim/general/general.vim
source $HOME/.config/vim/general/abb.vim
source $HOME/.config/vim/keybindings/keybindings.vim
source $HOME/.config/vim/plugins/plugins.vim


" Important!!
if has('termguicolors')
   set termguicolors
endif

colorscheme wal 

syntax enable
