#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.local/bin/restart_mate_panel.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          0
bspc rule -a Xfce4-panel state=floating layer=above
bspc rule -a Mate-panel layer=above state=floating
#bspc config top_padding 30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# تجاهل اللوحة وعدم التحكم بها
bspc rule -a Mate-Panel state=floating sticky=on layer=above

