#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10



#### BSPWM configuration ####
# hover with mouse
bspc config focus_follows_pointer true


#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color	      "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



# تجاهل اللوحة وعدم التحكم بها
bspc rule -a Mate-Panel state=floating sticky=on layer=above

~/.local/bin/restart_mate_panel.sh &
