#! /bin/sh
# Terminate already running bar instances
killall -q polybar 
# Wait until the processes have been shut down
# while pgrep -x polybar >/dev/null; do sleep 1; done
# Launch
polybar -c ~/.config/polybar/config.ini &
sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Keep the Arch Linux container running in the background for instant app startup
distrobox-enter arch-box -- sh -c "while true; do sleep infinity; done" &

#### BSPWM configuration ####
# hover with mouse
bspc config focus_follows_pointer true


#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color	      "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



bspc rule -a mpv desktop='^4'
